### ISSUE TITLE
从LCFCN过来请教

### ISSUE THREAD

**Issue by GloriaZLQ** [tongpinmo/learning-documents#1]
关于LCFCN，想请教一下，你用自己数据复现成功了吗，如果要套用自己数据，用什么工具标注point，生成dots.png，还有怎么生成.mat文件呀？？？可否微信交流一下呢（gloria_zlq）

**Comment by tongpinmo** [comment]
ok , 标注我们没有标注，还是跟任务有关吧，得根据你的数据类型做dataloader,生成jsonfile

**Comment by GloriaZLQ** [comment]
想问一下，你们标注point用的什么工具呢？如何准确标注物体中心点，还是大致？

**Comment by tongpinmo** [comment]
标数据这种繁琐的事没做啊，中心点大致的
